### ISSUE TITLE
[1] Create Club Collections / Publications / defaultClubs (settings.development.json)

### ISSUE THREAD

**Issue by pamanuel** [mongo-mongoers/club-hub#4]
Do all work for this task in a branch called issue-04
Clubs properties are name, appreviation, logo, email, image, goal, description

**Comment by mgpauly1458** [comment]
I added the Clubs and ProfilesClubs collection. ProfilesClubs will be used similar to the WOD to allow us to make a many to many relation between profiles and clubs. We can query them similar to how we did in the WOD earlier. They were both tested and are publishing one default item that was read in from settings.json (tested with Studio 3T).
